baseURL = "https://polu.subinsb.com/"
languageCode = "en-us"
title = "CryptoPolu"
theme = "material-design"
copyright = "© 2017 CryptoPolu"

[params]
    description = "Get signals when a market gets unexpected rise on CryptoCurrency Exchanges" # optional
    gitlab = "subins2000" # optional
    github = "subins2000" # optional
    googleAnalyticsUserID = "UA-33042168-4" # optional
    disqusShortname = "subinsblog"

[permalinks]
    post = "/:title" # optional

[[menu.icon]]
    url = "https://github.com/subins2000/polu.subinsb.com"
    name = "github"
    weight = 1
